### ISSUE TITLE
It doesn't seem like this will update the time more than once

### ISSUE THREAD

**Issue by vvv-ca** [ClassTech/NtpTime#2]
Hi, 
am I missing something or is there a missing timer->start()? According to the particle docs: "a newly created timer is stopped"?

Also, in case of success you set synced to true but never reset it back to false in case of future failures?

And finally, according to the particle docs you need to call changePeriodFromISR instead of changePeriod since most of the calls should be happening from the ISR.

**Comment by ClassTech** [comment]
"Hi,"

Hi.  Thanks for the detailed review and your comments.

"am I missing something or is there a missing timer->start()? According to the particle docs: "a newly created timer is stopped"?"

Yep, they do say that.  But the timer starts anyway.  I'll add an explicit start() when I get a chance.

"Also, in case of success you set synced to true but never reset it back to false in case of future failures?"

The synced variable is meant to show we have had at least one successful sync to cover the interval between startup and the first sync.  If there is a use case that needs it to be reset on failure, we can look into it.

"And finally, according to the particle docs you need to call changePeriodFromISR instead of changePeriod since most of the calls should be happening from the ISR."

I read this as an ambiguity in the docs.  They say: "The timer callback is similar to an interrupt - it shouldn't block. However, it is less restrictive than an interrupt."   My read is that the timer callback is not and ISR.  The current code does the job.  Should it stop working, I'll keep this in mind.

Thanks again,
Doug
