### ISSUE TITLE
Time Zone

### ISSUE THREAD

**Issue by fariqghani** [ClassTech/NtpTime#4]
Hi.
How do I set up the Time Zone?

Thanks..

**Comment by ClassTech** [comment]
NTP time is Universal Time as Unix epoch time, the number of seconds since midnight January 1, 1970.  If you want to keep a local time, you can apply whatever conversion is appropriate for you.  So for US Central Standard Time, you would take NTP time and subtract 21600 (6 hours times 3600 seconds).
-- Doug

**Comment by fariqghani** [comment]
where can I add the offset?

**Comment by ClassTech** [comment]
After fetching the time and before using it, add the offset to adjust to local time.  You do it in your code, not NTP.
